### ISSUE TITLE
Make networkx an optional dependency

### ISSUE THREAD

**Issue by scottgigante** [loukasa/graph-coarsening#4]
From what I can see, networkx is only used in the example notebooks, and not in the actual codebase. Any chance you would support removing networkx from `setup.py` and instead adding a `!pip install networkx` cell at the top of the notebooks? It's a pretty hefty dependency given that it's not actually used in the coarsening code.

**Comment by loukasa** [comment]
it's a good idea. I will try to do it.

**Comment by scottgigante** [comment]
Thanks!
