### ISSUE TITLE
Question about coarsening matrix

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [loukasa/graph-coarsening#6]
Hello,

Thank you very much for sharing the code. I am mainly using your code for another project so I mainly use ``C, Gc, Call, Gall = coarsen(G, K=k, r=r, method=method)``.

C is the coarsening matrix. To my understanding, it corresponds to the matrix P is the JMLR paper. If that's the case, then by property 10, P*1_N = 1_n. But I did a quick test, the output is not a vector of all ones. I modify from the coarsening_demo.ipynb. Let me know if I misunderstand anything. 

Thank you!
Chen

**Comment by loukasa** [comment]
Hello Chen, 

C is different from P. You can read this https://github.com/loukasa/graph-coarsening/issues/2#issuecomment-550281976 for a detailed explanation!

best
andreas

**Comment by Chen-Cai-OSU** [comment]
Great! Thank you!
